#!/bin/bash

while [ -n "$1" ] ; do
	case $1 in
		vassar|brandeis|gigaword|galaxy|evaluation|manager) cd $1 && sudo make && sudo make push ;;
		all)
			for p in vassar brandeis gigaword galaxy evaluation manager ; do
				cd $p && sudo make && sudo make push
			done
			;;
		*) echo "Unknown image $1" ;;
	esac
	shift
done
echo "Done."
