#!/bin/bash

# script for some simple checks of the instance


# show files in root directory (useful because we tend to put an
# identity file there that indicates what instance we are in)

echo
echo $ find / -maxdepth 1 -type f -printf '%f\n'
find / -maxdepth 1 -type f -printf '%f\n'

# show directory listings 

echo
echo $ ls /var/local/corpora
ls /var/local/corpora

echo
echo $ ls /var/local/galaxy/galaxy-central
ls /var/local/galaxy/galaxy-central


# test existence of integrated_tool_panel.xml

if [ ! -f /var/local/galaxy/galaxy-central/integrated_tool_panel.xml ]
then
	echo
	echo "WARNING: integrated_tool_panel.xml does not exist"
fi

# show docker images and processes

echo
echo $ docker images
sudo docker images

echo
echo $ docker ps -a
sudo docker ps -a
