#!/bin/bash

# Script to pull latest code from github (master branch) and to
# overwrite the old versions of scripts in /usr/local/bin

cd /discovery-course
echo "Pulling code from github..."
git pull
echo "Copying scripts to /usr/local/bin..."
cp scripts/* /usr/local/bin
ls -alF /usr/local/bin
